# Generated by Django 4.2.7 on 2024-12-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='player_images/')),
                ('description', models.TextField()),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['country', 'name'],
            },
        ),
    ]
